filegroup(
    name = "folder",
    srcs = ["."],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "headers",
    srcs = glob([
        "playground/*.h",
        "playground/*.inl",
    ]),
    visibility = ["//visibility:public"],
)
